version: '3.5'

services:
  postgres:
    container_name: full_stack_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fill-stack-shop
    restart: unless-stopped

  pgadmin:
    container_name: full_stack_db_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - fill-stack-shop
    restart: unless-stopped
    user: "${UID}:${GID}"

networks:
  fill-stack-shop:
    driver: bridge