# This is a basic workflow to help you get started with Actions

name: Node.js CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: main
    # Steps represent a sequence of tasks that will be executed as part of the jobs
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3      
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/Development/Node_Shop
          git pull origin main
          git status 
          rm -rf node_modules
          rm -rf package-lock.json
          npm install
          pm2 restart node-shop-server
